version: "3.4"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
services:
  publicatie:
    restart: "no"
  dispatcher:
    restart: "no"
  identifier:
    ports:
      - "8080:80"
    restart: "no"
    environment:
      SESSION_COOKIE_SECURE: "false"
      # SAME_SITE: "None" doesn't work with insecure cookies
      SESSION_COOKIE_SAME_SITE: "Lax"
  database:
    restart: "no"
  virtuoso:
    restart: "no"
    ports:
      - 8890:8890
    volumes:
      - ./config/db/virtuoso.dev.ini:/data/virtuoso.ini
    # environment:
    #   BACKUP_PREFIX: "virtuoso_backup_200914T0330-"
  migrations:
    restart: "no"
  cache:
    restart: "no"
  besluit-publicatie:
    restart: "no"
  publicatie-melding:
    restart: "no"
    command: "/bin/false" # overwrite when testing
  resource:
    restart: "no"
  deltanotifier:
    restart: "no"
  published-resource-consumer:
    restart: "no"
  taskmetrics:
    restart: "no"
  file:
    restart: "no"
    volumes:
        - ../app-gelinkt-notuleren/data/files/:/share/
  sparql-cache:
    restart: "no"
  cooluri:
    restart: "no"
  # # enable the following for linking the consumer to a local stack
  # # assumes the app-gn stack is running locally on your host
  # # and you've renamed the identifier to identifier-gelinkt-notuleren
  # published-resource-consumer:
  #   image: lblod/gelinkt-notuleren-consumer
  #   restart: "no"
  #   environment:
  #     NODE_ENV: development
  #     SERVICE_NAME: 'published-resource-consumer'

  #     SYNC_BASE_URL: 'http://identifier-gelinkt-notuleren'
  #     INGEST_INTERVAL: 60000
  #   volumes:
  #     - ./config/consumer/:/config/
  #   networks:
  #     - default
  #     - gelinkt-notuleren

  # networks:
  #   gelinkt-notuleren:
  #     external:
  #       name: app-gelinkt-notuleren_default
