version: "3.4"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
services:
  publicatie:
    image: lblod/frontend-gelinkt-notuleren-publicatie:1.4.0
    mem_limit: 4g
    links:
      - identifier:backend
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  dispatcher:
    image: semtech/mu-dispatcher:2.0.0
    volumes:
      - ./config/dispatcher:/config
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  identifier:
    image: semtech/mu-identifier:1.10.1
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
    environment:
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: "[{\"variables\":[],\"name\":\"public\"}]"
      DEFAULT_ACCESS_CONTROL_ALLOW_ORIGIN_HEADER: '*'
  database:
    image: semtech/mu-authorization:0.6.0-beta.6
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
    volumes:
      - ./config/authorization:/config
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  virtuoso:
    image: redpencil/virtuoso:1.2.0-rc.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/db/virtuoso.ini:/data/virtuoso.ini
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  migrations:
    image: semtech/mu-migrations-service:0.7.0
    links:
      - virtuoso:database
    volumes:
      - ./config/migrations:/data/migrations
    environment:
      MU_SPARQL_TIMEOUT: "600"
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  cache:
    image: semtech/mu-cache:2.0.2
    links:
      - resource:backend
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  besluit-publicatie:
    image: lblod/besluit-publicatie-publish-service:0.12.2
    links:
      - database:database
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  publicatie-melding:
    image: lblod/besluit-publicatie-melding-service:0.6.1
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
    links:
      - database:database
    environment:
      RESCHEDULE_CRON_PATTERN: '15 7 * * *'
  resource:
    image: semtech/mu-cl-resources:1.23.0
    volumes:
      - ./config/resources:/config
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    labels:
      - "logging=true"
    environment:
      CACHE_CLEAR_PATH: "http://cache/.mu/clear-keys"
  deltanotifier:
    image: semtech/mu-delta-notifier:0.1.0
    volumes:
      - ./config/delta:/config
    restart: always
  published-resource-consumer:
    image: lblod/gelinkt-notuleren-consumer:0.2.2
    environment:
      SERVICE_NAME: 'published-resource-consumer'
#      SYNC_BASE_URL: 'http://[dev.]gelinkt-notuleren.lblod.info'
      INGEST_INTERVAL: 60000
      BATCH_SIZE: 5
    restart: always
    volumes:
      - ./config/consumer/:/config/
  taskmetrics:
    image: lblod/task-metrics-service:1.0.0
    links:
      - database:database
  file:
    image: semtech/mu-file-service:3.1.0
    links:
      - database:database
  sparql-cache:
    image: redpencil/varnish-post:1.0.0
    environment:
      BACKEND_HOST: database
    restart: always
  cooluri:
    image: nvdk/cool-uris:1.0.0
    environment:
      SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
      PORT: 80
