version: "3.4"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
services:
  publicatie:
    image: lblod/frontend-gelinkt-notuleren-publicatie:0.15.1
    links:
      - identifier:backend
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    volumes:
      - ./config/dispatcher:/config
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  identifier:
    image: semtech/mu-identifier:1.8.1
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
    environment:
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: "[{\"variables\":[],\"name\":\"public\"}]"
      DEFAULT_ACCESS_CONTROL_ALLOW_ORIGIN_HEADER: '*'
  database:
    image: semtech/mu-authorization:0.6.0-beta.3
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
    volumes:
      - ./config/authorization:/config
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  virtuoso:
    image: tenforce/virtuoso
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/db/virtuoso.ini:/data/virtuoso.ini
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  migrations:
    image: semtech/mu-migrations-service:0.5.0
    links:
      - virtuoso:database
    volumes:
      - ./config/migrations:/data/migrations
    environment:
      MU_SPARQL_TIMEOUT: "600"
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  cache:
    image: semtech/mu-cache:2.0.1
    links:
      - resource:backend
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  besluit-publicatie:
    image: lblod/besluit-publicatie-publish-service:0.5.0
    links:
      - database:database
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  publicatie-melding:
    image: lblod/besluit-publicatie-melding-service:0.3.7
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
    links:
      - database:database
  resource:
    image: semtech/mu-cl-resources:1.18.0
    volumes:
      - ./config/resources:/config
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    labels:
      - "logging=true"

  deltanotifier:
    image: semtech/mu-delta-notifier:0.1.0
    volumes:
      - ./config/delta:/config
    restart: always
  dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    volumes:
      - ./config/dispatcher:/config
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  published-resource-consumer:
    image: lblod/gelinkt-notuleren-consumer:0.1.4
    environment:
      SERVICE_NAME: 'published-resource-consumer'
      SYNC_BASE_URL: 'http://docker-host'
      INGEST_INTERVAL: 60000
    volumes:
      - ./config/consumer/:/config/
