version: "3.4"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
services:
  publicatie:
    ports:
      - 8080:80
    restart: "no"
  identifier:
    restart: "no"
  database:
    restart: "no"
  virtuoso:
    restart: "no"
    ports:
      - 8890:8890
    volumes:
      - ./config/db/virtuoso.dev.ini:/data/virtuoso.ini
    # environment:
    #   BACKUP_PREFIX: "virtuoso_backup_200914T0330-"
  migrations:
    restart: "no"
  cache:
    restart: "no"
  besluit-publicatie:
    restart: "no"
  publicatie-melding:
    restart: "no"
    command: "/bin/false" # overwrite when testing

  published-resource-consumer:
    image: lblod/gelinkt-notuleren-consumer
    restart: "no"
    environment:
      NODE_ENV: development
      SERVICE_NAME: 'published-resource-consumer'
      # assumes the app-gn stack is running locally on your host
      SYNC_BASE_URL: 'http://published-resource-producer'
      INGEST_INTERVAL: 60000
    volumes:
      - ./config/consumer/:/config/
    networks:
      - default
      - gelinkt-notuleren

  networks:
    gelinkt-notuleren:
      external:
        name: app-gelinkt-notuleren_default
